In [1]:
import pandas as pd
df = pd.read_csv('feature_code_to_name_mapping.csv')
df.head()

  Feature Code                                       Feature Name
0   DP02_0001E     Estimate!!HOUSEHOLDS BY TYPE!!Total households
1   DP02_0001M  Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...
2   DP02_0002E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
3   DP02_0002M  Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...
4   DP02_0003E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...

In [3]:
#remove rows where the feature code ends with "M"
df = df[~df['Feature Code'].str.endswith('M')]
df.head()

  Feature Code                                       Feature Name
0   DP02_0001E     Estimate!!HOUSEHOLDS BY TYPE!!Total households
2   DP02_0002E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
4   DP02_0003E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
6   DP02_0004E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
8   DP02_0005E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...

In [4]:
# export
df.to_csv('feature_code_to_name_mapping_clean.csv', index=False)